### ISSUE TITLE
Failed to download habitat matterport dataset

### ISSUE THREAD

**Issue by Ending2015a** [facebookresearch/habitat-challenge#101]
Hello, I want to download the habitat matterport dataset from command line.
I use the following command in *the docker container*
```python
python -m habitat_sim.utils.datasets_download --username <secret-token> --password <secret-password> --uids hm3d_val --data-path habitat-challenge-data/
```

However I get the following results:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    56  100    56    0     0     33      0  0:00:01  0:00:01 --:--:--    33
Traceback (most recent call last):
  File "/opt/conda/envs/habitat/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/habitat/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 584, in <module>
    main(sys.argv[1:])
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 579, in main
    uid, data_path, args.username, args.password, replace
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/habitat_sim-0.2.1-py3.7-linux-x86_64.egg/habitat_sim/utils/datasets_download.py", line 416, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/opt/conda/envs/habitat/lib/python3.7/tarfile.py", line 1580, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by srama2512** [comment]
@Ending2015a  You will have to use the latest main version of habitat-sim for the downloads to work as expected. The docker has an older version I believe.

**Comment by dhruvbatra** [comment]
Actually, I'm not seeing anything downloaded in that log. The mostly likely cause is that you didn't actually get permission to download HM3D.

**Comment by Ending2015a** [comment]
@dhruvbatra @srama2512 Thank you very much.
I successfully download the dataset and semantic data with the latest version of habitat sim and habitat lab. The problem is that I passed my account password to the `--password` argument, then I realized that it should be the *API token secrete*, not the password.
