### ISSUE TITLE
libllvmlite.so not found in the docker image

### ISSUE THREAD

**Issue by mhtsbt** [facebookresearch/habitat-challenge#105]
When I try to run the docker image:
```
docker run --rm -i -t --runtime nvidia objectnav_submission:latest
```
I get the following error:

```
Traceback (most recent call last):
  File "agent.py", line 7, in <module>
    import habitat
  File "/habitat-lab/habitat/__init__.py", line 8, in <module>
    from habitat.core.agent import Agent
  File "/habitat-lab/habitat/core/agent.py", line 13, in <module>
    from habitat.core.simulator import Observations
  File "/habitat-lab/habitat/core/simulator.py", line 13, in <module>
    import quaternion
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/quaternion/__init__.py", line 31, in <module>
    from .quaternion_time_series import (
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/quaternion/quaternion_time_series.py", line 10, in <module>
    from quaternion.numba_wrapper import njit
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/quaternion/numba_wrapper.py", line 13, in <module>
    from numba import njit, jit, vectorize, int64, float64, complex128
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/numba/core/config.py", line 15, in <module>
    import llvmlite.binding as ll
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/opt/conda/envs/habitat/lib/python3.7/site-packages/llvmlite/binding/ffi.py", line 195, in <module>
    raise OSError(msg)
OSError: Could not load shared object file: libllvmlite.so
Errors were: [OSError("/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/envs/habitat/lib/python3.7/site-packages/llvmlite/binding/../../../../libLLVM-11.so)"), OSError('libllvmlite.so: cannot open shared object file: No such file or directory'), OSError('./libllvmlite.so: cannot open shared object file: No such file or directory'), OSError("/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/envs/habitat/lib/python3.7/site-packages/llvmlite/binding/../../../../libLLVM-11.so)")]
```
I have attempted to get the latest version (docker pull) multiple times, and have purged all local docker images.

This is the Dockerfile I'm using:

```
FROM fairembodied/habitat-challenge:testing_2022_habitat_base_docker

RUN /bin/bash -c ". activate habitat; pip install torch scipy==1.7.3"

ADD agent.py agent.py
ADD ppo_agent/ ppo_agent/
ADD submission.sh submission.sh
ADD configs/challenge_objectnav2022.local.rgbd.yaml /challenge_objectnav2022.local.rgbd.yaml
ENV AGENT_EVALUATION_TYPE remote

ENV TRACK_CONFIG_FILE "/challenge_objectnav2022.local.rgbd.yaml"

CMD ["/bin/bash", "-c", "source activate habitat && export PYTHONPATH=/evalai-remote-evaluation:$PYTHONPATH && export CHALLENGE_CONFIG_FILE=$TRACK_CONFIG_FILE && bash submission.sh"]
```

**Comment by dhruvbatra** [comment]
Were you able to successfully test `Objectnav_DDPPO_baseline.Dockerfile` via `test_locally_objectnav_rgbd.sh`? 

CC: @ykarmesh

**Comment by ykarmesh** [comment]
We have heard about this issue previously but I haven't encountered it personally. While I do not have a concrete answer to it at the moment, @mhtsbt can you try the solutions mentioned in this [issue](https://github.com/jacobkrantz/VLN-CE/issues/4) and report back if it solves it for you?

**Comment by mhtsbt** [comment]
Thanks, adding the following before everything else in agent.py solves the issue:
```
import habitat; import torch; import quaternion
```
