### ISSUE TITLE
unable to install habitat-sim with challenge version

### ISSUE THREAD

**Issue by duanyiqun** [facebookresearch/habitat-challenge#140]
Hi there, appreciate a lot for the great work. 

Seems the habitat-sim version for challenge 2023 is not feasible to install. 
I tried with two machines: 1) an ubuntu 18.0.4 cmake 3.14.0 local machine 2) a ubuntu 18.0.4 cmake 3.16.0. 
It gives the error below:

```sh
conda install -c aihabitat habitat-sim-challenge-2023
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - python=3.7 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.27
```

seems the current version 2.27 satisfied requirement 2.17. But the error still appears

May I get some instructions to resolve this?

**Comment by ykarmesh** [comment]
It has worked for me. I am tagging @aclegg3 who might be able to help you out.

**Comment by duanyiqun** [comment]
> It has worked for me. I am tagging @aclegg3 who might be able to help you out.

Thanks very much for your reply. Do you have any idea about how this would happen? 　
If it is convenient, may I know your GCC version?

**Comment by duanyiqun** [comment]
Dear all, 

I think I solved this problem by force with conda-forge, however new problem appears that seems even the challenge version of habitat lacks a action called KeyError: 'VELOCITY_CTRL'
please refer to errors below. 

```sh
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 287, in __init__
    self.sim_config = self.create_sim_config(self._sensor_suite)
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 380, in create_sim_config
    )(self.habitat_config).get()
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/actions.py", line 201, in get
    HabitatSimActions.VELOCITY_CTRL: habitat_sim.ActionSpec(
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/actions.py", line 77, in __getattr__
    return self._known_actions[name]
KeyError: 'VELOCITY_CTRL'
Error executing job with overrides: []
Traceback (most recent call last):
  File "habitat_baselines/run.py", line 31, in main
    execute_exp(cfg, "eval" if cfg.habitat_baselines.evaluate else "train")
  File "habitat_baselines/run.py", line 60, in execute_exp
    trainer.train()
  File "/home/yiqduan/Data/anaconda3/envs/habitat_challenge/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat_baselines/rl/ppo/ppo_trainer.py", line 725, in train

```

**Comment by ykarmesh** [comment]
What version of habitat lab are you using?

**Comment by duanyiqun** [comment]
> What version of habitat lab are you using?

I'm using the branch main. Since the branch mentioned in the readme  --branch challenge-2023 is not existing in the repo.

**Comment by twoongg** [comment]
Also suffering same issue with my local machine Ubuntu 20.04.
