### ISSUE TITLE
Can't find corresponding habitat-lab version for training, actionspae mismatch.

### ISSUE THREAD

**Issue by duanyiqun** [facebookresearch/habitat-challenge#141]
Hi team, thank you very much for the great work. 

I'm currently following tutorial 2023 for the habitat challenge. 

I found the tag you mentioned in the readme.MD is not accessible. 

```sh
git clone --branch challenge-2023 https://github.com/facebookresearch/habitat-lab.git
Cloning into 'habitat-lab'...
fatal: Remote branch challenge-2023 not found in upstream origin
Unexpected end of command stream
```
However, when I try to reproduce the results by using the main branch habitat. I found that the action space does not match. 
I print the current action space, seems velocity control is not under is part. 

```sh
    HabitatSimActions.VELOCITY_CTRL: habitat_sim.ActionSpec(
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/actions.py", line 80, in __getattr__
    return self._known_actions[name]
KeyError: 'VELOCITY_CTRL'
{'stop': 0, 'move_forward': 1, 'turn_left': 2, 'turn_right': 3, 'look_up': 4, 'look_down': 5, 'arm_action': 6, 'arm_vel': 7, 'arm_abs_pos': 8, 'arm_abs_pos_kinematic': 9, 'suction_grasp': 10, 'magic_grasp': 11, 'base_velocity': 12, 'arm_ee': 13, 'empty': 14, 'rearrange_stop': 15, 'humanoidjoint_action': 16}
Process ForkServerProcess-3:
Traceback (most recent call last):
  File "/home/yiqduan/Data/anaconda3/envs/habitat_challenge/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yiqduan/Data/anaconda3/envs/habitat_challenge/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yiqduan/Data/anaconda3/envs/habitat_challenge/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 251, in _worker_env
    env = EnvCountEpisodeWrapper(EnvObsDictWrapper(env_fn(*env_fn_args)))
  File "/projects/CIBCIGroup/00DataUploading/yiqun/habitat_data/codes/habitat-2023/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 100, in __call__

```

May I get some instructions?

Hope you have a great day.

**Comment by ykarmesh** [comment]
Hi Yiqun, 

The challenge will be officially released tomorrow. You will be able to see the `challenge-2023` tag for habitat-lab after that.

**Comment by duanyiqun** [comment]
> Hi Yiqun,
> 
> The challenge will be officially released tomorrow. You will be able to see the `challenge-2023` tag for habitat-lab after that.

Great, thank you very much for that. 
Cheers.

**Comment by ykarmesh** [comment]
@duanyiqun Sorry for the delay. Can you try to install habitat-lab with the `challenge-2023` tag now?
