### ISSUE TITLE
Error when try to local evaluate : "6. Evaluate your docker container locally" 

### ISSUE THREAD

**Issue by Huangbuffer** [facebookresearch/habitat-challenge#171]
Hi, this erro seems to let me find some problems in data, but my data is download form https://github.com/matterport/habitat-matterport-3dresearch, and I download hm3d-minival-glb-v0.2.tar to the path.
then give the comand to cmd:
**./scripts/test_local_objectnav.sh --docker-name objectnav_submission**

Run it and I got an erro says:
pybullet build time: Oct 28 2022 16:15:14
Neither `ifconfig` (`ifconfig -a`) nor `ip` (`ip address show`) commands are available, listing network interfaces is likely to fail
2023-05-12 08:16:14,781 Initializing dataset ObjectNav-v1
2023-05-12 08:16:14,871 initializing sim Sim-v0
[08:16:14:922727]:[Metadata] StageAttributesManager.cpp(86)::registerObjectFinalize : Render asset template handle : habitat-challenge-data/data/scene_datasets/hm3d_v0.2/minival/00802-wcojb4TFT35/wcojb4TFT35.basis.glb specified in stage template with handle : habitat-challenge-data/data/scene_datasets/hm3d_v0.2/minival/00802-wcojb4TFT35/wcojb4TFT35.basis.glb does not correspond to any existing file or primitive render asset.  Aborting.
Traceback (most recent call last):
  File "agent.py", line 86, in <module>
    main()
  File "agent.py", line 78, in main
    challenge = habitat.Challenge(eval_remote=False, action_space=args.action_space)
  File "/habitat-lab/habitat-lab/habitat/core/challenge.py", line 16, in __init__
    super().__init__(
  File "/habitat-lab/habitat-lab/habitat/core/benchmark.py", line 47, in __init__
    self._env = Env(config=config_env)
  File "/habitat-lab/habitat-lab/habitat/core/env.py", line 114, in __init__
    self._sim = make_sim(
  File "/habitat-lab/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 289, in __init__
    super().__init__(self.sim_config)
  File "<attrs generated init habitat_sim.simulator.Simulator>", line 11, in __init__
  File "/opt/conda/envs/habitat/lib/python3.8/site-packages/habitat_sim-0.2.3-py3.8-linux-x86_64.egg/habitat_sim/simulator.py", line 119, in __attrs_post_init__
    self.__set_from_config(self.config)
  File "/opt/conda/envs/habitat/lib/python3.8/site-packages/habitat_sim-0.2.3-py3.8-linux-x86_64.egg/habitat_sim/simulator.py", line 274, in __set_from_config
    self._config_backend(config)
  File "/opt/conda/envs/habitat/lib/python3.8/site-packages/habitat_sim-0.2.3-py3.8-linux-x86_64.egg/habitat_sim/simulator.py", line 201, in _config_backend
    super().__init__(config.sim_cfg, config.metadata_mediator)
**AssertionError: ESP_CHECK failed: Missing (at least) one of scene dataset attributes, stage attributes, or dataset scene attributes for scene 'habitat-challenge-data/data/scene_datasets/hm3d_v0.2/minival/00802-wcojb4TFT35/wcojb4TFT35.basis.glb'.  Likely an invalid scene name.**

Do u know how to solve this problem? Thank u very much!

**Comment by Huangbuffer** [comment]
and I tried other 2 minival datasets, the erro still there

**Comment by Huangbuffer** [comment]
I got it, Just need change the file name  "hm3d-minival-glb-v0.2" to "minival"
