### ISSUE TITLE
AssertionError: Object attributes not uniquely matched to shortened handle.

### ISSUE THREAD

**Issue by taylorlulu** [facebookresearch/habitat-challenge#183]
I met this problem:
```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/lu/.conda/envs/hab-mm/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/lu/.conda/envs/hab-mm/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lu/.conda/envs/hab-mm/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/core/vector_env.py", line 262, in _worker_env
    observations = env.reset()
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/core/gym_env_episode_count_wrapper.py", line 50, in reset
    return self.env.reset(**kwargs)
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/core/gym_env_obs_dict_wrapper.py", line 32, in reset
    return self.env.reset(**kwargs)
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/utils/gym_adapter.py", line 287, in reset
    obs = self._env.reset()
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/core/environments.py", line 47, in reset
    observations = super().reset()
  File "/home/lu/.conda/envs/hab-mm/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/core/env.py", line 402, in reset
    return self._env.reset()
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/core/env.py", line 250, in reset
    self.reconfigure(self._config)
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/core/env.py", line 336, in reconfigure
    self._sim.reconfigure(self._config.SIMULATOR)
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 223, in reconfigure
    self._add_objs(ep_info, should_add_objects)
  File "/home/lu/Desktop/embodied_ai/hab-mobile-manipulation/habitat-lab/habitat/tasks/rearrange/rearrange_sim.py", line 409, in _add_objs
    ), f"Object attributes not uniquely matched to shortened handle. '{obj_handle}' matched to {matching_templates}. TODO: relative paths as handles should fix some duplicates. For now, try renaming objects to avoid collision."
AssertionError: Object attributes not uniquely matched to shortened handle. '004_sugar_box.object_config.json' matched to {}. TODO: relative paths as handles should fix some duplicates. For now, try renaming objects to avoid collision.
```

I tried to debug with pycharm and found that the problem was caused by 

https://github.com/facebookresearch/habitat-lab/blob/0f454f62e41050bc90ca468c62db35d7484923ff/habitat/tasks/rearrange/rearrange_sim.py#L419-L432

the `len(matching_templates.values()) == 0`, and the matching_templates turns out to be empty.

**Comment by taylorlulu** [comment]
I found that in pick.yaml: 
https://github.com/facebookresearch/habitat-lab/blob/0f454f62e41050bc90ca468c62db35d7484923ff/configs/tasks/rearrange/pick.yaml#L123-L125

the ADDITIONAL_OBJECT_PATHS is "data/objects/ycb/configs/". However I'm using ycb_1.1 which doesn't have the configs folder. Then I switched to the ycb_1.2 folder. The problem was solved.
