### ISSUE TITLE
Unable to run PointNav agent locally

### ISSUE THREAD

**Issue by mohankumarSriram** [facebookresearch/habitat-challenge#23]
While running the "test_locally_pointnav_rgbd.sh" script, I get the following error:
```
2020-03-24 10:15:01,170 Initializing dataset PointNav-v1
2020-03-24 10:15:01,171 initializing sim Sim-v0
2020-03-24 10:15:02,310 Initializing task Nav-v0
Traceback (most recent call last):
  File "agent.py", line 26, in <module>
    main()
  File "agent.py", line 21, in main
    challenge = habitat.Challenge()
  File "/habitat-api/habitat/core/challenge.py", line 16, in __init__
    super().__init__(config_paths)
  File "/habitat-api/habitat/core/benchmark.py", line 30, in __init__
    self._env = Env(config=config_env)
  File "/habitat-api/habitat/core/env.py", line 102, in __init__
    dataset=self._dataset,
  File "/habitat-api/habitat/tasks/registration.py", line 21, in make_task
    return _task(**kwargs)
  File "/habitat-api/habitat/tasks/nav/nav.py", line 968, in __init__
    super().__init__(config=config, sim=sim, dataset=dataset)
  File "/habitat-api/habitat/core/embodied_task.py", line 241, in __init__
    entities_config=config,
  File "/habitat-api/habitat/core/embodied_task.py", line 269, in _init_entities
    entity_type = register_func(entity_cfg.TYPE)
  File "/opt/conda/envs/habitat/lib/python3.6/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: TYPE
```
When I traced the error, I found that the task type specified in "challenge_pointnav2020.local.rgbd.yaml" file is not being read by yacs. Please let me know how I can fix this problem.

**Comment by AdventureO** [comment]
@mathfac please help! Got the same problem after latest commit

**Comment by dhruvbatra** [comment]
I'm seeing the same thing at my end. Sorry :-(. We are working on it.

**Comment by abhiskk** [comment]
@AdventureO we updated the master branch, you should try testing now.

We made some changes to our configs, can you pull the latest version of code. Also do make sure that when you are building the docker that the cached docker images are not used.

Best is to run a `docker system prune -a` which will remove all the cached images, and build the dockers again.

**Comment by dhruvbatra** [comment]
Can confirm. This works for me now.

**Comment by mohankumarSriram** [comment]
Works with the latest code, Thank you @abhiskk and @dhruvbatra :)

**Comment by mathfac** [comment]
@AdventureO should be fixed now, can you confirm from your side?

**Comment by AdventureO** [comment]
@mathfac yes, it works for me now. Thanks!
