### ISSUE TITLE
Cannot run  tests, wrong checkpoint?  torch.Size([128, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([82, 1024, 3, 3]).

### ISSUE THREAD

**Issue by giadefa** [facebookresearch/habitat-challenge#71]
I followed these instructions on ubuntu:
https://colab.research.google.com/gist/mathfac/8c9b97d7afef36e377f17d587c903ede#scrollTo=Qo_z277BAueV

But when I run the test I get:

```
(base) ggg:~/habitat/habitat-challenge$ bash ./test_locally_pointnav_rgbd.sh --docker-name ddppo_pointnav_submission
Neither `ifconfig` (`ifconfig -a`) nor `ip` (`ip address show`) commands are available, listing network interfaces is likely to fail
Checkpoint loaded: demo.ckpt.pth
/habitat-lab/habitat_baselines/config/default.py:214: UserWarning: NUM_PROCESSES is depricated and will be removed in a future version.  Use NUM_ENVIRONMENTS instead.  Overwriting NUM_ENVIRONMENTS with NUM_PROCESSES for backwards compatibility.
  "NUM_PROCESSES is depricated and will be removed in a future version."
Traceback (most recent call last):
  File "agent.py", line 200, in <module>
    main()
  File "agent.py", line 189, in main
    agent = DDPPOAgent(config)
  File "agent.py", line 124, in __init__
    for k, v in ckpt["state_dict"].items()
  File "/opt/conda/envs/habitat/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PointNavResNetPolicy:
	Missing key(s) in state_dict: "net.pointgoal_embedding.weight", "net.pointgoal_embedding.bias". 
	Unexpected key(s) in state_dict: "net.tgt_embeding.weight", "net.tgt_embeding.bias". 
	size mismatch for net.visual_encoder.compression.0.weight: copying a param with shape torch.Size([128, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([82, 1024, 3, 3]).
	size mismatch for net.visual_encoder.compression.1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([82]).
	size mismatch for net.visual_encoder.compression.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([82]).
	size mismatch for net.visual_fc.1.weight: copying a param with shape torch.Size([512, 2048]) from checkpoint, the shape in current model is torch.Size([512, 2050]).
```

Any suggestion?

**Comment by bucherb** [comment]
The default values for the class PointNavResNetPolicy changed in the latest stable version which cause the provided pretrained models provided on [this ReadMe](https://github.com/facebookresearch/habitat-lab/tree/master/habitat_baselines/rl/ddppo) to not run correctly.

To get the same PointNavResNetPolicy those models were trained with, use the parameters num_recurrent_layers=2, rnn_type="LSTM", backbone="resnet50" in the constructor.

**Comment by mathfac** [comment]
Thank you for the issue we are following with the update for the checkpoint and baseline config change.

**Comment by mathfac** [comment]
@giadefa, please pull latest docker and habitat-challenge repo and let me know if ddppo local testing working for you. Thank you!

**Comment by giadefa** [comment]
All working.
