### ISSUE TITLE
No such file or directory: 'habitat-challenge-data/objectgoal_mp3d/val_mini/val_mini.json.gz'

### ISSUE THREAD

**Issue by ethanabrooks** [facebookresearch/habitat-challenge#76]
Hi. I am trying to run the `test_locally_objectnav_rgbd.sh` script with the provided `RandomAgent`. I am following the [Local Evaluation instruction](https://github.com/facebookresearch/habitat-challenge#local-evaluation):

1. Cloned the master branch
2. Built the `objectnav_submission` image using 
```
docker build . --file Objectnav.Dockerfile -t objectnav_submission
```
3. Nvidia-docker installed and working
4. No modifications to the Dockerfile. Using all defaults.
5. This is my directory structure:
```
tree habitat-challenge-data
habitat-challenge-data
├── data
│   ├── datasets
│   │   └── objectnav
│   │       └── mp3d
│   │           └── v1
│   │               ├── objectnav_mp3d_v1.zip
│   │               ├── train
│   │               │   ├── content
│   │               │   │   ├── 17DRP5sb8fy.json.gz
│   │               │   │   ├── 1LXtFkjw3qL.json.gz
│   │               │   │   ├── 1pXnuDYAj8r.json.gz
│   │               │   │   ├── 29hnd4uzFmX.json.gz
│   │               │   │   ├── 5LpN3gDmAk7.json.gz
│   │               │   │   ├── 5q7pvUzZiYa.json.gz
│   │               │   │   ├── 759xd9YjKW5.json.gz
│   │               │   │   ├── 7y3sRwLe3Va.json.gz
│   │               │   │   ├── 82sE5b5pLXE.json.gz
│   │               │   │   ├── 8WUmhLawc2A.json.gz
│   │               │   │   ├── aayBHfsNo7d.json.gz
│   │               │   │   ├── ac26ZMwG7aT.json.gz
│   │               │   │   ├── B6ByNegPMKs.json.gz
│   │               │   │   ├── b8cTxDM8gDG.json.gz
│   │               │   │   ├── cV4RVeZvu5T.json.gz
│   │               │   │   ├── D7G3Y4RVNrH.json.gz
│   │               │   │   ├── D7N2EKCX4Sj.json.gz
│   │               │   │   ├── dhjEzFoUFzH.json.gz
│   │               │   │   ├── E9uDoFAP3SH.json.gz
│   │               │   │   ├── e9zR4mvMWw7.json.gz
│   │               │   │   ├── EDJbREhghzL.json.gz
│   │               │   │   ├── GdvgFV5R1Z5.json.gz
│   │               │   │   ├── gZ6f7yhEvPG.json.gz
│   │               │   │   ├── HxpKQynjfin.json.gz
│   │               │   │   ├── i5noydFURQK.json.gz
│   │               │   │   ├── JeFG25nYj2p.json.gz
│   │               │   │   ├── JF19kD82Mey.json.gz
│   │               │   │   ├── jh4fc5c5qoQ.json.gz
│   │               │   │   ├── kEZ7cmS4wCh.json.gz
│   │               │   │   ├── mJXqzFtmKg4.json.gz
│   │               │   │   ├── p5wJjkQkbXX.json.gz
│   │               │   │   ├── Pm6F8kyY3z2.json.gz
│   │               │   │   ├── pRbA3pwrgk9.json.gz
│   │               │   │   ├── PuKPg4mmafe.json.gz
│   │               │   │   ├── PX4nDJXEHrG.json.gz
│   │               │   │   ├── qoiz87JEwZ2.json.gz
│   │               │   │   ├── r1Q1Z4BcV1o.json.gz
│   │               │   │   ├── r47D5H71a5s.json.gz
│   │               │   │   ├── rPc6DW4iMge.json.gz
│   │               │   │   ├── s8pcmisQ38h.json.gz
│   │               │   │   ├── S9hNv5qa7GM.json.gz
│   │               │   │   ├── sKLMLpTHeUy.json.gz
│   │               │   │   ├── sT4fr6TAbpF.json.gz
│   │               │   │   ├── ULsKaCPVFJR.json.gz
│   │               │   │   ├── uNb9QFRL6hY.json.gz
│   │               │   │   ├── ur6pFq6Qu1A.json.gz
│   │               │   │   ├── Uxmj2M2itWa.json.gz
│   │               │   │   ├── V2XKFyX4ASd.json.gz
│   │               │   │   ├── VFuaQ6m2Qom.json.gz
│   │               │   │   ├── VLzqgDo317F.json.gz
│   │               │   │   ├── VVfe2KiqLaN.json.gz
│   │               │   │   ├── Vvot9Ly1tCj.json.gz
│   │               │   │   ├── vyrNrziPKCB.json.gz
│   │               │   │   ├── XcA2TqTSSAj.json.gz
│   │               │   │   ├── YmJkqBEsHnH.json.gz
│   │               │   │   └── ZMojNkEp431.json.gz
│   │               │   └── train.json.gz
│   │               ├── val
│   │               │   ├── content
│   │               │   │   ├── 2azQ1b91cZZ.json.gz
│   │               │   │   ├── 8194nk5LbLH.json.gz
│   │               │   │   ├── EU6Fwq7SyZv.json.gz
│   │               │   │   ├── oLBMNvg9in8.json.gz
│   │               │   │   ├── pLe4wQe7qrG.json.gz
│   │               │   │   ├── QUCTc6BB5sX.json.gz
│   │               │   │   ├── TbHJrupSAjP.json.gz
│   │               │   │   ├── X7HyMhZNoso.json.gz
│   │               │   │   ├── x8F5xyUWy9e.json.gz
│   │               │   │   ├── Z6MFQCViBuw.json.gz
│   │               │   │   └── zsNo4HB9uLZ.json.gz
│   │               │   └── val.json.gz
│   │               └── val_mini
│   │                   └── val_mini.json.gz
│   └── scene_datasets
│       └── mp3d
│           ├── download_mp.py
│           └── v1
│               └── scans
│                   └── 17DRP5sb8fy
│                       ├── cameras.zip
│                       ├── matterport_camera_intrinsics.zip
│                       ├── matterport_camera_poses.zip
│                       ├── matterport_color_images.zip
│                       └── tmp0PJfol
├── objectgoal_mp3d
│   └── val_mini
│       └── val_mini.json.gz
└── pointgoal_gibson_v2
    └── val_mini
        ├── content
        │   └── Pablo.json.gz
        └── val_mini.json.gz

```
6. Running the evaluation script:
```
❯ ./test_locally_objectnav_rgbd.sh --docker-name objectnav_submission

2021-03-19 13:32:25,265 Initializing dataset ObjectNav-v1
Traceback (most recent call last):
  File "agent.py", line 41, in <module>
    main()
  File "agent.py", line 33, in main
    challenge = habitat.Challenge(eval_remote=False)
  File "/habitat-lab/habitat/core/challenge.py", line 16, in __init__
    super().__init__(config_paths, eval_remote=eval_remote)
  File "/habitat-lab/habitat/core/benchmark.py", line 38, in __init__
    self._env = Env(config=config_env)
  File "/habitat-lab/habitat/core/env.py", line 79, in __init__
    id_dataset=config.DATASET.TYPE, config=config.DATASET
  File "/habitat-lab/habitat/datasets/registration.py", line 20, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/habitat-lab/habitat/datasets/object_nav/object_nav_dataset.py", line 74, in __init__
    super().__init__(config)
  File "/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 93, in __init__
    with gzip.open(datasetfile_path, "rt") as f:
  File "/opt/conda/envs/habitat/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/opt/conda/envs/habitat/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'habitat-challenge-data/objectnav_mp3d/val_mini/val_mini.json.gz'
```

Thanks for your help with this!

**Comment by dhruvbatra** [comment]
CC: @mathfac

**Comment by mathfac** [comment]
Looking into this.

**Comment by ethanabrooks** [comment]
It looks like at some point the name changed from `habitat-challenge/habitat-challenge-data/objectnav_mp3d` to `habitat-challenge/habitat-challenge-data/objectgoal_mp3d`. Simply renaming the directory fixed it for me.

**Comment by jzhzhang** [comment]
@ethanabrooks  Hi, sorry to reopen this issue because I meet the same error. Differently, I successfully run the script locally and obtain the performance of the agent. However, when I submit the docker image to remote and get the following error:
```
itat/core/benchmark.py", line 38, in __init__
    self._env = Env(config=config_env)
  File "/habitat-lab/habitat/core/env.py", line 78, in __init__
    id_dataset=config.DATASET.TYPE, config=config.DATASET
  File "/habitat-lab/habitat/datasets/registration.py", line 21, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/habitat-lab/habitat/datasets/object_nav/object_nav_dataset.py", line 74, in __init__
    super().__init__(config)
  File "/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 93, in __init__
    with gzip.open(datasetfile_path, "rt") as f:
  File "/opt/conda/envs/habitat/lib/python3.7/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/opt/conda/envs/habitat/lib/python3.7/gzip.py", line 168, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'habitat-challenge-data/objectgoal_hm3d/val_mini/val_mini.json.gz'
```

It's strange because I do not counter this problem on my own server. And I believe the evaluation platform should perform as normal. The problem seems related to the directory structure of the dataset. So is there any advice about this error?
