### ISSUE TITLE
Socket timeout issue while doing evalai push

### ISSUE THREAD

**Issue by devendrachaplot** [facebookresearch/habitat-challenge#9]
I ran the following command for evalai push
`evalai push gp_nav_rgbd:latest --phase habitat19-rgbd-minival`

and got the following error:
```
Traceback (most recent call last):
  File "/home/dchaplot/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/home/dchaplot/anaconda3/lib/python3.6/site-packages/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/home/dchaplot/anaconda3/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/home/dchaplot/anaconda3/lib/python3.6/http/client.py", line 483, in readinto
    return self._readinto_chunked(b)
  File "/home/dchaplot/anaconda3/lib/python3.6/http/client.py", line 578, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/home/dchaplot/anaconda3/lib/python3.6/http/client.py", line 546, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/home/dchaplot/anaconda3/lib/python3.6/http/client.py", line 506, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/dchaplot/anaconda3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

My docker image is 7.67GB.

What might be the issue here?

**Comment by RishabhJain2018** [comment]
Hey, @devendrachaplot Can you please check if you are on some proxy or VPN or the connection is very slow? The images of this size can be pushed easily.

**Comment by devendrachaplot** [comment]
I am not using any proxy or VPN. When I tried to push again, it worked really fast, using previously cached docker images.
